# WCSim config file for ROOT->HDF5 conversion

data:
  file_name:
  output_file:
  n_photons: 1
  nevents_per_file: 10000
  root_branches:
      event_info:
        - [pid, np.int32, 1]
        - [position, np.float32, 3]
        - [direction, np.float32, 3]
        - [energy, np.float32, 1]
      hit_photons:
        - [PE, np.int32, 10184]
        - [end_time, np.float32, '']
        - [end_position, np.float32, '']
        - [start_time, np.float32, '']
        - [start_position, np.float32, '']
        - [track, np.int32, '']
      digi_hits:
        - [pmt, np.int32, 10184] # pmt id
        - [charge, np.float32, 10184]
        - [time, np.float32, 10184]
        - [trigger, np.int32, 10184] # pmt trigger id
      tracks:
        - [id, np,int32, '']
        - [pid, np.int32, '']
        - [start_time, np.float32, '']
        - [energy, np.float32, '']
        - [start_position, np.float32, '']
        - [stop_position, np.float32, '']
        - [parent, np.int32, '']
        - [flag, np.int32, '']
      trigger:
        - [time, np.float32, '']
        - [type, np.int32, '']

detector:
  npmts: 10184
  
format:
  compression: gzip
  compression_opt: 5
